### ISSUE TITLE
about self.j in LexActorCritic class

### ISSUE THREAD

**Issue by zcyyyyyyyyyyy** [lrhammond/lmorl#6]
in class LexActorCritic, i think the variable self.j is the kj in the paper, self.recent_loss[:][-1] is the Kj in the paper, the question is i don't know why in the code self.j[i]=-mean(self.recent_loss[i]), i think it should be self.j[i]=mean(self.recent_loss[i]), because in the paper lambda(i+1)=max(0,lambda(i)+eta*(kj-tao-Kj).

**Comment by lrhammond** [comment]
Thanks for flagging this! You are correct – I have now pushed a fix to the main branch.
